events {}
http {
  server {
    listen 443 ssl;
    ssl_certificate     /certs/bank.local+5.pem;
    ssl_certificate_key /certs/bank.local+5-key.pem;
    location / {
      proxy_set_header Host $host;
      proxy_pass http://host.docker.internal:3001;
    }
  }
}

